### ISSUE TITLE
Security alert on dodas requirements

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/mesos-cluster#16]
Hi @MircoT 
can you please have a look at https://github.com/indigo-dc/mesos-cluster/network/alerts?
Thanks

**Comment by MircoT** [comment]
I can't open the alert. Is it the link correct?

**Comment by maricaantonacci** [comment]
Can you see this?
https://github.com/indigo-dc/mesos-cluster/network/alert/deploy/openstack-heat/dodas/requirements.txt/requests/open

**Comment by MircoT** [comment]
No, I can't. I have a 404 error...

**Comment by maricaantonacci** [comment]
ok I will send you an email

**Comment by MircoT** [comment]
Done. The alert should be disappeared...
